const clubs = {};
const shortNames = {};
const names = {};

/*
  cox: 'City of Oxford Rowing Club',
  crc: 'Chesterton Rowing Club',
  ley: 'Leys School Boat Club',
  oxb: 'Oxford Brookes University Boat Club',
  pet: 'Peterborough City Rowing Club',
  rob: 'Rob Roy Boat Club',
  srg: 'St Radegund Boat Club',
  trc: 'Thames Rowing Club',
  xpr: 'X-Press Boat Club',
  yrk: 'York City Rowing Club',
*/

clubs.uk = ['cab', 'cam', 'cha', 'cnn', 'sne'];

shortNames.uk = {
  cab: 'Cantabrigian',
  cam: 'City of Cambridge',
  cha: 'Champion Of The Thames',
  cnn: 'Cambridge 99',
  cox: 'City of Oxford',
  crc: 'Chesterton',
  ley: 'Leys School',
  oxb: 'Oxford Brookes University',
  pet: 'Peterborough City',
  rob: 'Rob Roy',
  sne: 'St Neots',
  srg: 'St Radegund',
  trc: 'Thames',
  xpr: 'X-Press',
  yrk: 'York City',
};

names.uk = {
  cab: 'Cantabrigian Rowing Club',
  cam: 'City of Cambridge Rowing Club',
  cha: 'Champion Of The Thames Rowing Club',
  cnn: 'Cambridge 99 Rowing Club',
  cox: 'City of Oxford Rowing Club',
  crc: 'Chesterton Rowing Club',
  ley: 'Leys School Boat Club',
  oxb: 'Oxford Brookes University Boat Club',
  pet: 'Peterborough City Rowing Club',
  rob: 'Rob Roy Boat Club',
  sne: 'St Neots Rowing Club',
  srg: 'St Radegund Boat Club',
  trc: 'Thames Rowing Club',
  xpr: 'X-Press Boat Club',
  yrk: 'York City Rowing Club',
};

/*
  fit: 'Fitzwilliam College Boat Club',
*/

clubs.cambridge = [
  'cai',
  'cco',
  'chu',
  'cla',
  'clh',
  'cor',
  'daw',
  'dow',
  'emm',
  'ftt',
  'gir',
  'hom',
  'huh',
  'jec',
  'kcb',
  'lmb',
  'mgd',
  'mec',
  'nnm',
  'pem',
  'pbc',
  'qcc',
  'roc',
  'sel',
  'sid',
  'scc',
  'sec',
  'trh',
  'woc',
];

shortNames.cambridge = {
  cai: 'Caius',
  cco: "Christ's College",
  chu: 'Churchill College',
  cla: 'Clare',
  clh: 'Clare Hall',
  cor: 'Corpus Christi College',
  daw: 'Darwin College',
  dow: 'Downing College',
  emm: 'Emmanuel',
  ftt: 'First and Third Trinity',
  fit: 'Fitzwilliam College',
  gir: 'Girton College',
  hom: 'Homerton College',
  huh: 'Hughes Hall',
  jec: 'Jesus College',
  kcb: "King's College",
  lmb: 'Lady Margaret',
  mgd: 'Magdalene',
  mec: 'Murray Edwards College',
  nnm: 'Newnham College',
  pem: 'Pembroke College',
  pbc: 'Peterhouse',
  qcc: "Queens' College",
  roc: 'Robinson College',
  sel: 'Selwyn College',
  sid: 'Sidney Sussex',
  scc: "St. Catharine's College",
  sec: "St. Edmund's College",
  trh: 'Trinity Hall',
  woc: 'Wolfson College',
};

names.cambridge = {
  cai: 'Caius Boat Club',
  cco: "Christ's College Boat Club",
  chu: 'Churchill College Boat Club',
  cla: 'Clare Boat Club',
  clh: 'Clare Hall Boat Club',
  cor: 'Corpus Christi College Boat Club',
  daw: 'Darwin College Boat Club',
  dow: 'Downing College Boat Club',
  emm: 'Emmanuel Boat Club',
  ftt: 'First and Third Trinity Boat Club',
  fit: 'Fitzwilliam College Boat Club',
  gir: 'Girton College Boat Club',
  hom: 'Homerton College Boat Club',
  huh: 'Hughes Hall Boat Club',
  jec: 'Jesus College Boat Club',
  kcb: "King's College Boat Club",
  lmb: 'Lady Margaret Boat Club',
  mgd: 'Magdalene Boat Club',
  mec: 'Murray Edwards College Boat Club',
  nnm: 'Newnham College Boat Club',
  pem: 'Pembroke College Boat Club',
  pbc: 'Peterhouse Boat Club',
  qcc: "Queens' College Boat Club",
  roc: 'Robinson College Boat Club',
  sel: 'Selwyn College Boat Club',
  sid: 'Sidney Sussex Boat Club',
  scc: "St. Catharine's College Boat Club",
  sec: "St. Edmund's College Boat Club",
  trh: 'Trinity Hall Boat Club',
  woc: 'Wolfson College Boat Club',
};

/*
  lmh: 'Lady Margaret Hall Boat Club',
  lin: 'Linacre Boat Club',
  lic: 'Lincoln College Boat Club',
  osg: 'Osler House Boat Club',
  say: 'St Antony's College Boat Club',
  sjo: 'St John's College Boat Club',
  wro: 'Worcester College Boat Club',
*/

clubs.oxford = [
  'bal',
  'brc',
  'chb',
  'coo',
  'exc',
  'gtm',
  'hec',
  'jeo',
  'keb',
  'mag',
  'man',
  'mer',
  'nec',
  'oro',
  'pmb',
  'qco',
  'rpc',
  'som',
  'sac',
  'sbh',
  'sco',
  'seh',
  'shi',
  'shg',
  'spc',
  'tro',
  'uxo',
  'wad',
  'woo',
];

shortNames.oxford = {
  bal: 'Balliol College',
  brc: 'Brasenose College',
  chb: 'Christ Church',
  coo: 'Corpus Christi College',
  exc: 'Exeter College',
  gtm: 'Green Templeton',
  hec: 'Hertford College',
  jeo: 'Jesus College',
  keb: 'Keble College',
  mag: 'Magdalen College',
  man: 'Mansfield College',
  mer: 'Merton College',
  nec: 'New College',
  oro: 'Oriel College',
  pmb: 'Pembroke College',
  qco: "The Queen's College",
  rpc: "Regent's Park College",
  som: 'Somerville College',
  sac: "St Anne's College",
  sbh: "St Benet's Hall",
  sco: "St Catherine's College",
  seh: 'St Edmund Hall',
  shi: "St Hilda's College",
  shg: "St Hugh's College",
  spc: "St Peter's College",
  tro: 'Trinity College',
  uxo: 'University College',
  wad: 'Wadham College',
  woo: 'Wolfson College',
};

names.oxford = {
  bal: 'Balliol College Boat Club',
  brc: 'Brasenose College Boat Club',
  chb: 'Christ Church Boat Club',
  coo: 'Corpus Christi College Boat Club',
  exc: 'Exeter College Boat Club',
  gtm: 'Green Templeton Boat Club',
  hec: 'Hertford College Boat Club',
  jeo: 'Jesus College Boat Club',
  keb: 'Keble College Boat Club',
  mag: 'Magdalen College Boat Club',
  man: 'Mansfield College Boat Club',
  mer: 'Merton College Boat Club',
  nec: 'New College Boat Club',
  oro: 'Oriel College Boat Club',
  pmb: 'Pembroke College Boat Club',
  qco: "The Queen's College Boat Club",
  rpc: "Regent's Park College Boat Club",
  som: 'Somerville College Boat Club',
  sac: "St Anne's College Boat Club",
  sbh: "St Benet's Hall Boat Club",
  sco: "St Catherine's College Boat Club",
  seh: 'St Edmund Hall Boat Club',
  shi: "St Hilda's College Boat Club",
  shg: "St Hugh's College Boat Club",
  spc: "St Peter's College Boat Club",
  tro: 'Trinity College Boat Club',
  uxo: 'University College Boat Club',
  wad: 'Wadham College Boat Club',
  woo: 'Wolfson College Boat Club',
};

export { clubs, names, shortNames };
